### ISSUE TITLE
doAction implementation

### ISSUE THREAD

**Issue by zaksmithcomputing** [acorbin3/P3achB0t#37]
research into implementing doAction for instant interactions with objects and also then looking into spoofing mouse data for those interactions

**Comment by acorbin3** [comment]
Looks like ZAk hooked it but we still need to figure out what's required for it to work. 

- [x] Add a call back where the parts get printed so we can see what's required

**Comment by acorbin3** [comment]
Fixed the invocation but still lots of room for improvement on how the interactions will work.

**Comment by acorbin3** [comment]
This mainly has been set up can complete. Will continue to add as needed
