### ISSUE TITLE
doAction overrides

### ISSUE THREAD

**Issue by zaksmithcomputing** [acorbin3/P3achB0t#45]
I'm currently looking into Overriding doAction parameters when they are invoked. 

https://i.imgur.com/wNbVoPH.png - methods which are invoked when calling doAction

The idea would be to use a boolean injected into these methods in which is by default off so when using the mouse in game legitimately it does not interfere with gameplay. If the boolean is switched on (by a method we create e.g named overridedoAction) then the parameters will be set by the function within that method and the doaction would be called from the click with altered params and then the boolean switched off again.

**Comment by acorbin3** [comment]
Complete and in master
