### ISSUE TITLE
Inventory issues

### ISSUE THREAD

**Issue by zaksmithcomputing** [acorbin3/P3achB0t#48]
Seems to be an issue detecting the slot at which an item is in the inventory also the inventory paint is not displaying not sure if the issue is correlated or not. Bank paint not displaying. Also having issues with ground items again. It seems like these issues could all be linked

**Comment by acorbin3** [comment]
Ended up that the rest of was fixed by enabling Side-panels in the Advanced options
https://puu.sh/F9qxl/b05de80470.png

or stuff was commented out.
